server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://123.57.241.191:3306/db_sams?serverTimezone=Asia/Shanghai
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
  mvc:
    view:
      prefix: /templates/
      suffix: .html
#    static-path-pattern: /static/**
  mail:
    host: smtp.qq.com
    username: 1506336555@qq.com
    password: bgghhijrvwwcfeif
    port: 25
    protocol: smtp
    default-encoding: UTF-8

ftp:
  hostname: 123.57.241.191
  port: 21
  username: ftpfile
  password: "000000"
  re-save-path: /sams/image
  save-path: /var/ftp/file/sams/image
