server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.30.50:3306/db_sams?serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  mail:
    host: smtp.qq.com
    username: 1506336555@qq.com
    password:
    port: 25
    protocol: smtp
    default-encoding: UTF-8
  redis:
    host: 192.168.30.50
    port: 6379
    timeout: 5000
    password:


ftp:
  hostname:
  port: 21
  username: ftpfile
  password:
  re-save-path: /sams/image
  save-path: /var/ftp/file/sams/image
